# batch/v1 tells it to use the JOB API
apiVersion: batch/v1
# we are running a Job, not a Pod
kind: Job

# set the name of the job
metadata:
  name: preprocessing

spec:
  template:
    spec:
      containers:
        - name: preprocessing
          image: docker.io/ctvqfq/bunny_ai:spie-1.2
          command: ["/bin/sh", "-c"]
          args: ["git clone https://github.com/Kovaleski-Research-Lab/surrogate_model.git .;
                    cd /develop/code/src/core;
                    python3 /develop/code/src/core/preprocess_data.py > /develop/results/kube_logs/preprocessing.log"]
          resources:
            limits:
              memory: 500G
              cpu: 40
              #nvidia.com/gpu: 1
            requests:
              memory: 400G
              cpu: 32
              #nvidia.com/gpu: 1
          volumeMounts:
            - name: meep-results
              mountPath: /develop/results
      volumes:
        - name: meep-results
          persistentVolumeClaim:
            claimName: meep-results
      restartPolicy: Never
