# Configuration: Meep Data Generation

# Define Paths
# - path_image: path to public container image
# - path_template: path to kubernetes job template
# - path_simulations: path to store simulations (pvc)
# - path_sim_job_files: path to store generated job files (local)

path_image: docker.io/ctvqfq/bunny_ai:spie-1.2
path_template: kube_files/templates/job.txt

path_simulations: /develop/results
path_logs: /develop/results/current_logs
path_sim_job_files: /develop/data/spie_journal_2023/kube_logs

# Define Computing Environment
# - num_mem_lim: limits of random access memory
# - num_mem_req: requested random access memory
# - num_cpus_per_op: number of cpus resource for each simulation, denote as a.
# - num_parallel_ops: number of simulations happening in parallel, Denoate as b.
# - num_cpus_total: number of cpus used at once in computing cluster, denote as c | c = a * b.

num_mem_lim: 240G
num_mem_req: 200G
num_cpus_per_op: 40
#num_cpus_total: 2048
num_parallel_ops: 2
#num_cpus_total: 160

namespace: gpn-mizzou-muem
kill_time_min: 30
#kill_tag: preprocess
kill_tag: sim

# Define Simulation

num_sims: 3000 # this is the ending index
start_group_id: 1489
