# batch/v1 tells it to use the JOB API
apiVersion: batch/v1
# we are running a Job, not a Pod
kind: Job

# set the name of the job
metadata:
  name: training

spec:
  template:
    spec:
      containers:
        - name: andy-train
          image: docker.io/ctvqfq/bunny_ai:spie-1.2
          #command: ["python3", "surrogate_model/src/core/preprocess_data.py"]
          command: ["/bin/sh", "-c"]
          args: ["git clone https://github.com/Kovaleski-Research-Lab/surrogate_model.git .; cd /develop/code/src/core; python3 /develop/code/src/core/preprocess_data.py > /develop/data/spie_journal_2023/kube_logs/test.log"]
          #args: ["git clone https://github.com/Kovaleski-Research-Lab/surrogate_model.git .; cd /develop/code/src/core; python3 preprocess_data.py > /develop/data/spie_journal_2023/train_logs/test.log"]
          #args: ["git clone https://github.com/Kovaleski-Research-Lab/surrogate_model.git .; cd /develop/code/src/core/; touch /develop/data/spie_journal_2023/kube_logs/test.txt"]
          resources:
            limits:
              memory: 240G
              cpu: 40
              #nvidia.com/gpu: 1
            requests:
              memory: 200G
              cpu: 32
              #nvidia.com/gpu: 1
          volumeMounts:
            - name: meep-results
              mountPath: /develop/results
      volumes:
        - name: meep-results
          persistentVolumeClaim:
            claimName: meep-results
      restartPolicy: Never
