apiVersion: v1
kind: Pod
metadata:
  name: monitor
spec:
  containers:
    - name: monitor
      image: docker.io/ctvqfq/bunny_ai:spie-1.2
      env:
        - name: RCLONE_NAUTILUS_TYPE
          value: s3
        - name: RCLONE_CONFIG_NAUTILUS_ENDPOINT
          value: http://rook-ceph-rgw-centrals3.rook-central
        - name: RCLONE_CONFIG_NAUTILUS_PROVIDER
          value: Other
        - name: RCLONE_CONFIG_NAUTILUS_ACCESS_KEY_ID
          value: JPKIHDAZY41Q5IPG1SPM
        - name: RCLONE_CONFIG_NAUTILUS_SECRET_ACCESS_KEY
          value: 2AZNOB1ivWEGKV1UYK6HDb5KuEJJ0s5dxDBxQPEE
      stdin: True
      tty: True
      resources:
        limits:
          memory: 8G
          cpu: 6
        requests:
          memory: 6G
          cpu: 6
      volumeMounts:
        - name: meep-results
          mountPath: /develop/results
  volumes:
    - name: meep-results
      persistentVolumeClaim:
        claimName: meep-results

  restartPolicy: Never

#export RCLONE_CONFIG_NAUTILUS_ACCESS_KEY_ID=JPKIHDAZY41Q5IPG1SPM
#export RCLONE_CONFIG_NAUTILUS_SECRET_ACCESS_KEY=2AZNOB1ivWEGKV1UYK6HDb5KuEJJ0s5dxDBxQPEE
#envsubst < monitor_pod.yaml | kubectl apply -f -
