apiVersion: v1
kind: Pod
metadata:
  name: jupyter
spec:
  containers:
    - name: jupyter-testing
      image: docker.io/ctvqfq/bunny_ai:spie-1.2
      stdin: True
      tty: True
      resources:
        limits:
          memory: 16G
          cpu: 12
        requests:
          memory: 12G
          cpu: 12
      volumeMounts:
        - name: meep-results
          mountPath: /develop/results
  volumes:
    - name: meep-results
      persistentVolumeClaim:
        claimName: meep-results

  restartPolicy: Never
