resim : 

#--------------------------------
#       General Params - ML
#--------------------------------
seed: [True, 1337]
train: True
model_id: 'baseline'
#torch_home: '~/.cache/torch/'
torch_home: '/develop/pretrained_models'

#--------------------------------
#       Training Params
#--------------------------------
batch_size: 8
num_epochs: 200

accelerator: 'gpu' 
gpu_config: [True, [0]]

valid_rate: 1

weights: 
num_classes: 1
optimizer: 'ADAM'
backbone: 'resnet18'
learning_rate: 1.e-6
transfer_learn: False
load_checkpoint: False
objective_function: 'mse'

freeze_encoder: False

mcl_params:
    alpha: 1     #near-field
    beta: 1     #far-field
    gamma: 1    #phase
    delta: 1    #derivatives

#--------------------------------
#       All paths
#--------------------------------
#path_root: '/home/marshall/research/cai_2023'
path_root: '/develop/'
path_data: 'data/'
path_train: 'train/'
path_valid: 'valid/'
path_model: 'model_checkpoints/'
path_results: 'results/'
path_checkpoint: 'model_checkpoints/model_baseline_phases_derivatives'
path_resims: 'resims/'

#--------------------------------
#       Physical Params
#--------------------------------

#Metasurface simulation
Nx_metaAtom: 3
Ny_metaAtom: 3
Lx_metaAtom: 680.e-9
Ly_metaAtom: 680.e-9

h_pillar: 102.e-9
thickness_pml: 780.e-9
thickness_fusedSilica: 780.e-9
thickness_PDMS: 1560.e-9

#General
wavelength: 1550.e-9

#Fourier propagation
distance: 10.e-6
Nxp: 176
Nyp: 176
Lxp: 2.04e-6
Lyp: 2.04e-6
adaptive: True

#--------------------------------
#       Datamodule Params
#--------------------------------
which: 'CAI'
n_cpus: 5

#-------------------------------
#   General Params - datagen
#-------------------------------

#------------------------
#   Material Parameters
#-------------------------

n_fusedSilica : 1.44
n_PDMS : 1.4
n_amorphousSi : 3.48

pml_thickness : 0.780
height_pillar : 1.020
radius :
rad_min : 0.075
rad_max : 0.250
width_PDMS : 1.560
width_fusedSilica : 0.780
non_pml :

center_PDMS :
center_fusedSilica :
center_pillar :

z_fusedSilica :
z_PDMS :
x_dim :
y_dim :
geometry :

#-----------------------
#   Source Parameters
#-----------------------

wavelength_1550 : 1.55
wavelength_1300 : 1.30
wavelength_1060 : 1.06
wavelength_1650 : 1.65
wavelength_2881 : 
fcen :
freq_1550 :
freq_1300 :
freq_1060 :
freq_1650 :
freq_2881 :
fwidth :
k_point :
center_source :
source_cmpt :
source_type : "gaussian"
source :
cell_x :
cell_y :
cell_z :
decay_rate : 0.0001

#------------------------
#   Simulation Parameters
#-------------------------

#resolution : 80
resolution : 40
lattice_size : 0.680
grid_size : 3 

cell_x :
cell_y :
cell_z :
cell_size :

pml_layers :
k_point :
pml_layers :
symmetries :

#------------------------
#   Flux Object Params
#------------------------

freq :
nfreq : 1 
freq_list :
df : 0 
fr_center :
fr :
#flux_object :
near_pt :
near_vol :

#-----------------------
#  Animation Params
#----------------------

plot_plane :
fps : 20
