resim : 0 
training_stage :

#--------------------------------
#       General Params - ML
#--------------------------------

torch_home: '/develop/pretrained_models'
seed: [True, 1337]
train: True
model_id: "baseline_1_nockpt"

exp_name: 
prev_model_id:

#--------------------------------
#       Training Params
#--------------------------------

batch_size: 16 
num_epochs: 100 

mcl_params:
    gamma: 0     # phase
    delta: 1     # derivatives
    epsilon: 0   # intensity 
    alpha: 0     # near-field

load_checkpoint: False # only False when doing first stage 
freeze_encoder: False 
 
transfer_learn: False

initial_intensities :
    2881: 2.133954817261386e-05
    1650: 0.020591382539901358
    1550: 0.02579922487539837
    1300: 0.013293813343678174
    1060: 0.00015713650643846212

weights: 
num_classes: 1
optimizer: 'ADAM'
backbone: 'resnet18'
learning_rate: 3.e-4
objective_function: 'mse'

accelerator: 'gpu' 
gpu_config: [True, [0]]

valid_rate: 1

#--------------------------------
#       All paths
#--------------------------------
path_root: '/develop/'
path_data: 'data/spie_journal_2023/kube_dataset/'
# 
path_results: 'results/spie_journal_2023/' #params.yaml, train and valid go here.
path_train: 'train/'
path_valid: 'valid/'
path_resims: 'resims/'
path_dataset: 

#--------------------------------
#       Datamodule Params
#--------------------------------
which: 'CAI'
n_cpus: 5
source_wl : 1550
Nxp: 166 # make this dynamic, put in parameter manager. it's data.shape
Nyp: 166
data_shape:

#------------------------
#   Material Parameters
#-------------------------

n_fusedSilica : 1.44
n_PDMS : 1.4
n_amorphousSi : 3.48

pml_thickness : 0.780
height_pillar : 1.020
radius :
rad_min : 0.075
rad_max : 0.250
width_PDMS : 1.560
width_fusedSilica : 0.780
non_pml :

center_PDMS :
center_fusedSilica :
center_pillar :

z_fusedSilica :
z_PDMS :
x_dim :
y_dim :
geometry :

#-----------------------
#   Source Parameters
#-----------------------

wavelengths : [2.881, 1.650, 1.550, 1.300, 1.060]
cen_wavelength : 1.55
fcen :
fwidth :
k_point :
center_source :
source_cmpt :
source_type : "gaussian"
source :
cell_x :
cell_y :
cell_z :
decay_rate : 0.0001
dt : 50

#------------------------
#   Simulation Parameters
#-------------------------

resolution : 80
lattice_size : 0.680
grid_size : 3 

cell_x :
cell_y :
cell_z :
cell_size :

pml_layers :
k_point :
pml_layers :
symmetries :

#------------------------
#   DFT Object Params
#------------------------

freq :
nfreq : 1 
freq_list :
df : 0 
mon_center :
near_pt :
near_vol :
cs :

#-----------------------
#  Animation Params
#----------------------

plot_plane :
fps : 20
